services:
  docharvest:
    build: .
    image: docharvest:7.0
    container_name: docharvest
    command: --help
    volumes:
      - type: bind
        source: ~/.docharvest
        target: /root/.docharvest
