"""The rename is only finished if it stays finished.

`gitbook-downloader` was the package name for every release up to 11.1.0. The
11.1.1 rename touched 122 files, and the failure mode of a rename this size is
not a crash — it is one forgotten install instruction, one stale badge, one
`pip install` in a modal that ships to users. These tests make the old name fail
loudly instead of quietly surviving in a corner of the product.

Two categories are allowed to say the old name, and only two:

* **History** — ``CHANGELOG.md`` and the audit in ``docs/CONSULTANT_REVIEW.md``
  quote what was true when they were written; rewriting them would make them lie.
* **The migration itself** — ``docharvest/paths.py`` and its test must name the
  legacy directory and environment variable, because moving a user's library off
  them is the entire point.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent

#: Files that may legitimately contain the retired name.
HISTORY = {"CHANGELOG.md", "docs/CONSULTANT_REVIEW.md"}
MIGRATION = {
    "src/docharvest/paths.py",
    "tests/test_library_migration.py",
    "tests/test_naming_drift.py",
    # Asserts the retired name is ABSENT from the README. The assertion is
    # the whole point of the file, so the literal has to be there.
    "tests/test_readme_contract.py",
}
# `marketing/` is deliberately untracked (see .gitignore), so nothing under it
# can be exempted: this guard only sees files git ships, and CI checks out a
# tree without them. An exemption for an untracked file fails on CI, not here.
GENERATED = {
    "uv.lock",
    "frontend/package-lock.json",
    "docs/package-lock.json",
    "repomix-architecture.xml",
}
EXEMPT = HISTORY | MIGRATION

SKIP_PARTS = ("node_modules", ".venv", ".git", "__pycache__", ".next", "/out/", "egg-info")
TEXT_SUFFIXES = {".py", ".ts", ".tsx", ".mjs", ".js", ".json", ".md", ".toml", ".yml", ".yaml",
                 ".tcss", ".html", ".txt", ".svg", ".cfg", ".ini", ".xml", ".sh", ".ps1"}

RETIRED = re.compile(r"gitbook[_-]download(er)?", re.I)


def _tracked_files() -> dict[str, Path]:
    """Every file git tracks — i.e. everything that ships or gets published.

    Scoped to tracked files on purpose: the working directory also holds large
    untracked scratch trees (a code-graph cache, a stale virtualenv, capture
    artifacts) that are derived data, not product surface. Chasing the old name
    through those would be dozens of megabytes of noise.
    """
    result = subprocess.run(
        ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
    )
    files: dict[str, Path] = {}
    for relative in result.stdout.split():
        path = ROOT / relative
        if path.is_file() and path.suffix.lower() in TEXT_SUFFIXES:
            files[relative] = path
    return files


def test_no_shipped_file_still_names_the_retired_package() -> None:
    offenders: dict[str, list[str]] = {}
    for relative, path in _tracked_files().items():
        if relative in EXEMPT or relative in GENERATED:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for number, line in enumerate(text.splitlines(), 1):
            if RETIRED.search(line):
                offenders.setdefault(relative, []).append(f"{number}: {line.strip()[:100]}")

    assert not offenders, (
        "the retired package name is still referenced:\n"
        + "\n".join(
            f"  {name}\n    " + "\n    ".join(lines[:3]) for name, lines in offenders.items()
        )
    )


def test_the_migration_still_knows_what_it_is_migrating_from() -> None:
    """Guard the allowance above: the exemption must stay narrow and real."""
    paths_source = (ROOT / "src" / "docharvest" / "paths.py").read_text(encoding="utf-8")
    assert 'LEGACY_LIBRARY_DIR_NAME = ".gitbook-downloader"' in paths_source
    assert 'ENV_HOME = "DOCHARVEST_HOME"' in paths_source
    assert "_LEGACY_ENV_HOME" in paths_source


@pytest.mark.parametrize("relative", sorted(EXEMPT))
def test_every_exemption_is_still_earned(relative: str) -> None:
    """An exemption that no longer names the old package is a hole, not a rule."""
    path = ROOT / relative
    assert path.exists(), f"{relative} is exempted but no longer exists — prune the exemption"
    assert RETIRED.search(path.read_text(encoding="utf-8")), (
        f"{relative} no longer mentions the retired name; remove it from the exemption list "
        f"so the guard keeps its teeth"
    )


def test_generated_files_are_regenerated_not_hand_edited() -> None:
    """Lockfiles may name the old package until they are regenerated by their tool."""
    for relative in sorted(GENERATED):
        path = ROOT / relative
        assert path.exists() or relative == "repomix-architecture.xml", (
            f"{relative} is missing — regenerate it"
        )


def test_one_name_across_every_public_surface() -> None:
    """pyproject, the registry manifest, the showcase and the README must agree."""
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    declared = re.search(r'^name = "([^"]+)"', pyproject, re.M)
    assert declared and declared.group(1) == "docharvest"

    manifest = json.loads((ROOT / "server.json").read_text(encoding="utf-8"))
    assert manifest["packages"][0]["identifier"] == declared.group(1), (
        "server.json publishes a different distribution than pyproject.toml declares"
    )

    stats = (ROOT / "docs" / "lib" / "stats.ts").read_text(encoding="utf-8")
    facts = re.search(r"packageName:\s*'([^']+)'", stats)
    assert facts and facts.group(1) == declared.group(1), (
        "the showcase advertises a different package name than the distribution"
    )

    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert "pip install docharvest" in readme or "uvx docharvest" in readme, (
        "README must show the current install command"
    )
    assert "pip install gitbook-downloader" not in readme


def test_console_scripts_match_the_new_name() -> None:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    scripts = pyproject.split("[project.scripts]", 1)[1].split("[", 1)[0]
    assert 'docharvest = "docharvest.cli:main"' in scripts
    assert "gitbook-dl" in scripts, "the documented short alias should survive the rename"
    assert "gitbook-downloader =" not in scripts, (
        "the old console script belongs to the retired package name"
    )


def test_package_data_is_declared_for_the_new_package() -> None:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    data = pyproject.split("[tool.setuptools.package-data]", 1)[1]
    assert data.strip().startswith("docharvest = ["), (
        "package-data must be keyed by the import package name, or the GUI/TUI/skill "
        "assets silently stop shipping"
    )
